"use client";

import { useState } from "react";
import {  useQuery, useMutation  } from "@/lib/convex-mock";
import { api } from "@/lib/convex-mock";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { toast } from "sonner";
import { Plus, Search, Edit, Trash2, Code2 } from "lucide-react";
import {
  Empty,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
  EmptyDescription,
  EmptyContent,
} from "@/components/ui/empty";

type FormData = {
  accountId: string;
  accountName: string;
  masterName: string;
  quality: string;
  clientCode: string;
  autoGenerated: boolean;
};

const defaultForm: FormData = {
  accountId: "",
  accountName: "",
  masterName: "",
  quality: "",
  clientCode: "",
  autoGenerated: false,
};

function generateCode(accountName: string, quality: string): string {
  const acctShort = accountName.trim().substring(0, 3).toUpperCase();
  const qualShort = quality.trim().substring(0, 3).toUpperCase();
  return `${acctShort}${qualShort}`;
}

export default function CodesPage() {
  const codes = useQuery(api.codeMaster.list, {});
  const accounts = useQuery(api.accounts.list, {});
  const createCode = useMutation(api.codeMaster.create);
  const updateCode = useMutation(api.codeMaster.update);
  const removeCode = useMutation(api.codeMaster.delete);

  const [search, setSearch] = useState("");
  const [open, setOpen] = useState(false);
  const [editId, setEditId] = useState<string | null>(null);
  const [form, setForm] = useState<FormData>(defaultForm);

  const millAccounts = (accounts ?? []).filter((a) => a.roleType === "Mill" && a.isActive);

  const filtered = (codes ?? []).filter(
    (c) =>
      c.accountName.toLowerCase().includes(search.toLowerCase()) ||
      c.clientCode.toLowerCase().includes(search.toLowerCase()) ||
      c.masterName.toLowerCase().includes(search.toLowerCase())
  );

  const set = (key: keyof FormData, value: string | boolean) => {
    setForm((prev) => {
      const updated = { ...prev, [key]: value };
      // Auto generate code when account or quality changes
      if ((key === "accountName" || key === "quality") && !prev.clientCode) {
        const code = generateCode(
          key === "accountName" ? String(value) : updated.accountName,
          key === "quality" ? String(value) : updated.quality
        );
        updated.clientCode = code;
        updated.autoGenerated = true;
      }
      return updated;
    });
  };

  const handleAccountSelect = (accountId: string) => {
    const acc = millAccounts.find((a) => a._id === accountId);
    if (acc) {
      const code = generateCode(acc.accountName, form.quality);
      setForm((prev) => ({
        ...prev,
        accountId,
        accountName: acc.accountName,
        clientCode: code,
        autoGenerated: true,
      }));
    }
  };

  const openNew = () => {
    setEditId(null);
    setForm(defaultForm);
    setOpen(true);
  };

  const openEdit = (c: NonNullable<typeof codes>[0]) => {
    setEditId(c._id);
    setForm({
      accountId: c.accountId,
      accountName: c.accountName,
      masterName: c.masterName,
      quality: c.quality,
      clientCode: c.clientCode,
      autoGenerated: c.autoGenerated,
    });
    setOpen(true);
  };

  const handleSave = async () => {
    if (!form.accountId || !form.masterName || !form.quality) {
      toast.error("Account, Master Name and Quality are required");
      return;
    }
    if (!form.clientCode) {
      toast.error("Client Code is required");
      return;
    }
    try {
      if (editId) {
        await updateCode({
          id: editId,
          accountName: form.accountName,
          masterName: form.masterName,
          quality: form.quality,
          clientCode: form.clientCode,
        });
        toast.success("Code updated");
      } else {
        await createCode({
          accountId: form.accountId as string,
          accountName: form.accountName,
          masterName: form.masterName,
          quality: form.quality,
          clientCode: form.clientCode,
          autoGenerated: form.autoGenerated,
        });
        toast.success("Code created");
      }
      setOpen(false);
    } catch {
      toast.error("Failed to save");
    }
  };

  const handleDelete = async (id: string) => {
    try {
      await removeCode({ id });
      toast.success("Deleted");
    } catch {
      toast.error("Failed to delete");
    }
  };

  return (
    <div className="p-6 space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold">Code Master</h1>
          <p className="text-sm text-muted-foreground">Manage Marka codes for account-quality combinations</p>
        </div>
        <Button onClick={openNew} className="cursor-pointer">
          <Plus size={16} className="mr-1" /> New Code
        </Button>
      </div>

      <div className="relative max-w-sm">
        <Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
        <Input
          className="pl-9"
          placeholder="Search by account, master or code..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
      </div>

      {codes === undefined ? (
        <div className="space-y-3">
          {Array.from({ length: 3 }).map((_, i) => <Skeleton key={i} className="h-14 w-full" />)}
        </div>
      ) : filtered.length === 0 ? (
        <Empty>
          <EmptyHeader>
            <EmptyMedia variant="icon"><Code2 /></EmptyMedia>
            <EmptyTitle>No codes found</EmptyTitle>
            <EmptyDescription>Create a code to link accounts with quality and generate Markas</EmptyDescription>
          </EmptyHeader>
          <EmptyContent>
            <Button size="sm" onClick={openNew} className="cursor-pointer">
              <Plus size={14} className="mr-1" /> Create Code
            </Button>
          </EmptyContent>
        </Empty>
      ) : (
        <div className="space-y-2">
          {filtered.map((c) => (
            <Card key={c._id} className="hover:shadow-sm transition-shadow">
              <CardContent className="flex items-center justify-between py-3 px-4">
                <div>
                  <div className="flex items-center gap-3">
                    <span className="font-bold text-primary text-sm bg-primary/10 px-2 py-0.5 rounded font-mono">
                      {c.clientCode}
                    </span>
                    <span className="font-medium text-sm">{c.accountName}</span>
                  </div>
                  <div className="flex items-center gap-3 mt-0.5 text-xs text-muted-foreground">
                    <span>Master: {c.masterName}</span>
                    <span>Quality: {c.quality}</span>
                    {c.autoGenerated && (
                      <span className="text-accent text-[10px] font-medium">Auto-generated</span>
                    )}
                  </div>
                </div>
                <div className="flex items-center gap-1">
                  <Button size="icon" variant="ghost" className="h-8 w-8 cursor-pointer" onClick={() => openEdit(c)}>
                    <Edit size={14} />
                  </Button>
                  <Button
                    size="icon"
                    variant="ghost"
                    className="h-8 w-8 cursor-pointer text-destructive hover:text-destructive"
                    onClick={() => handleDelete(c._id)}
                  >
                    <Trash2 size={14} />
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle>{editId ? "Edit Code" : "New Code"}</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 mt-2">
            <div className="space-y-1.5">
              <Label>Account (Mill) *</Label>
              <Select value={form.accountId} onValueChange={handleAccountSelect} disabled={!!editId}>
                <SelectTrigger>
                  <SelectValue placeholder="Select account..." />
                </SelectTrigger>
                <SelectContent>
                  {millAccounts.map((a) => (
                    <SelectItem key={a._id} value={a._id}>{a.accountName}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label>Master Name *</Label>
              <Input placeholder="Broker / Master name" value={form.masterName} onChange={(e) => set("masterName", e.target.value)} />
            </div>
            <div className="space-y-1.5">
              <Label>Quality *</Label>
              <Input
                placeholder="e.g. Cotton 60x60"
                value={form.quality}
                onChange={(e) => set("quality", e.target.value)}
              />
            </div>
            <div className="space-y-1.5">
              <Label>Client Code (Marka)</Label>
              <div className="flex gap-2">
                <Input
                  placeholder="Auto-generated or manual"
                  value={form.clientCode}
                  onChange={(e) => setForm((p) => ({ ...p, clientCode: e.target.value.toUpperCase(), autoGenerated: false }))}
                  className="font-mono"
                />
                <Button
                  variant="secondary"
                  className="cursor-pointer whitespace-nowrap"
                  onClick={() => {
                    const code = generateCode(form.accountName, form.quality);
                    setForm((p) => ({ ...p, clientCode: code, autoGenerated: true }));
                  }}
                >
                  Auto-gen
                </Button>
              </div>
            </div>
          </div>
          <div className="flex justify-end gap-2 mt-4">
            <Button variant="ghost" onClick={() => setOpen(false)} className="cursor-pointer">Cancel</Button>
            <Button onClick={handleSave} className="cursor-pointer">{editId ? "Update" : "Create"}</Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
